spring:
  application:
    name: KafkaConsumerProject
    kafka:
      bootstrap-servers: localhost:9092
      consumer:
        group-id: demo
        auto-offset-reset: earliest
    template:
      default-topic: orders
server:
  port: 8081